# Generated by Django 2.1.5 on 2019-01-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=30)),
                ('itemMainDescription', models.TextField(blank=True, max_length=30)),
                ('itemPointsDescription', models.TextField(blank=True, max_length=200)),
                ('itemImage', models.CharField(max_length=30)),
                ('itemPrice', models.FloatField()),
            ],
        ),
    ]
