# Generated by Django 2.1.5 on 2019-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemMainDescription',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
