# Generated by Django 2.2.6 on 2019-11-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190707_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemImage',
            new_name='item_image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemMainDescription',
            new_name='item_main_description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemPointsDescription',
            new_name='item_points_description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemPrice',
            new_name='item_price',
        ),
    ]
